# Generated by Django 4.1.4 on 2023-02-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='username',
        ),
    ]
